config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'
  patch '/tasks/:id/toggle_status', to: 'tasks#toggle_status', as: :toggle_status_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true 
  validates :body, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    # @tasks = Task.all
    @task_todo = Task.where(flag: 0)
    @task_done = Task.where(flag: 1)
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  # def show
  # end

  # GET /tasks/new
  # def new
  #   @task = Task.new
  # end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        # format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.html { redirect_to tasks_path, notice: 'success : 作成しました' }
        format.json { render :show, status: :created, location: @task }
      else
        # format.html { render :new }
        format.html { redirect_to tasks_path, notice: 'error : 作成できませんでした' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'success : 更新しました' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH /tasks/1/toggle_status
  def toggle_status
    @task = Task.find(params[:id])
    if @task.flag == 0
      @task.update_attribute(:flag, 1)
    else
      @task.update_attribute(:flag, 0)
    end
    redirect_to tasks_path, notice: 'success : 更新しました'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :body, :flag)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true, class: "index-page__form") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>

    <%= form.label :body %>
    <%= form.text_field :body, id: :task_body %>

    <%= form.submit yield(:name)%>

<% end %>

app/views/tasks/edit.html.erb
<% provide(:name, "更新") %>

<!--<h1>Editing Task</h1>-->

<%= render 'form', task: @task %>

<%#= link_to 'Show', @task %> 
<%#= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% provide(:name, "作成") %>

<p id="notice"><%= notice %></p>

<h1>TODOアプリ</h1>
<div class="index-page">
  <%= render 'form', task: @task %>
  <div class="index-page__tasks">
    
    <div class="index-page__task-list">
      <h2>TODO</h2>
      <div class="task-list">
        <% @task_todo.each do |task| %>
          <div class="task-list__item task">  
            <div class="task__name"><%= task.name %></div>
            <div class="task__body"><%= task.body %></div>
            <div class="task__buttons">
              <div class="task__edit">
                <%= link_to '編集', edit_task_path(task) %>
              </div>
              <div class="task__toggle">
                <%= link_to 'DONEにする', toggle_status_task_path(task), method: :patch  %>
              </div>          
            </div>
            <!--<td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="index-page__task-list">
      <h2>DONE</h2>
      <div class="task-list">
        <% @task_done.each do |task| %>
          <div class="task-list__item task">
            <div class="task__name"><%= task.name %></div>
            <div class="task__body"><%= task.body %></div>
            <div class="task__buttons">
              <div class="task__edit">
                <%= link_to '編集', edit_task_path(task) %>
              </div>
              <div class="task__toggle">
                <%= link_to 'TODOにする', toggle_status_task_path(task), method: :patch %>
              </div>          
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%#= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<% provide(:name, "作成") %>

<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>